### ISSUE TITLE
Deleting the last workspace should be prevented, or should be handled gracefully

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#116]
Deleting the last workspace is currently breaking the Console.

<img width="1680" alt="screen shot 2018-03-27 at 18 20 46" src="https://user-images.githubusercontent.com/1780597/37980772-33db208c-31ec-11e8-8a15-0d1cfaf4059c.png">

Either it should be prevented, or being handled gracefully.

If you are experiencing this issue, please create a new account or reach out to `support@graph.cool`.

**Comment by lydiahallie** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!
