### ISSUE TITLE
`prisma login` should let you sign in again if you're signed out of prisma dashboard

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#122]
@johhansantana commented on [Mon Apr 02 2018](https://github.com/graphcool/prisma/issues/2176)

# Bug Report

**Current behavior**
After signing out of prisma dashboard and trying to use `prisma login` via cli, it still would think I'm signed in in prisma dashboard

**Reproduction**

1. Sign in to prisma dashboard
2. Sign out of prisma dashboard
3. Use `prisma login` cli command
4. It will show you a page where you click on allow permissions button (but you are signed out, how does it know which account you're allowing permission)

**Expected behavior?**
It should show a form to sign in again

**Workarounds**
Open developer tools in app.prisma.sh and delete cache and cookies, it will let you sign in again after using `prisma login` command

**Comment by marktani** [comment]
Thanks a lot for reporting this issue and the workaround, @johhansantana! We'll look into this shortly 🙂

**Comment by lydiahallie** [comment]
This should be fixed by now. If this is still an issue, let us know and we reopen this!
