### ISSUE TITLE
Azure MySQL: "this user requires mysql native password authentication."

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#124]
This error is currently returned when setting up a new private cluster on Azure MySQL.

**Comment by JameelMukadam** [comment]
also when enabling SSL on Azure MySQL, the connection fails. Looks like something needs to be set on Prisma side to allow a SSL connection

**Comment by JameelMukadam** [comment]
Hi Guys. please can I get an update on this? is this on the radar to get fixed anytime soon?

**Comment by dpetrick** [comment]
@JameelMukadam MySQL SSL works with 1.18-beta and will be on 1.18 stable soon. Use `ssl: true` in the Prisma configs in the `databases:` > `default:` key, next to the user name, host, etc. of the database.

The Azure database user you use to connect to the DB has to be of the form: <username>@<host>, for example if your host is `testdb.mysql.database.azure.com`, it's <username>@testdb.
