### ISSUE TITLE
Last row of the table missing in Data Browser

### ISSUE THREAD

**Issue by valstu** [prisma/prisma-cloud-feedback#156]
When using Data Browser and when you have more than 50 rows on your table the last row is missing.

**How to reproduce:**
Create table with more than 50 rows. Browse to the bottom of the table, "lazy load" will load more items to your table. Let's say you have 64 rows, you will only see 63 rows. 

Probably index length issue with pagination I would guess?

**Comment by valstu** [comment]
Oh and noticed that there is actually empty row at the bottom of the table.

![image](https://user-images.githubusercontent.com/647861/40590686-9d0461e6-620b-11e8-99c1-255ebaec6d2e.png)

**Comment by lydiahallie** [comment]
This should be fixed by now. If it's still an issue, let us know and we reopen this!
