### ISSUE TITLE
Get error 404 from api on Data Browser page

### ISSUE THREAD

**Issue by sofrente** [prisma/prisma-cloud-feedback#162]
I've successfully setup self-hosted server and everything working fine (query, mutation) excepted I can't see anythings in Data browser.

`POST https://api.cloud.prisma.sh/ 404 ()`

<img width="776" alt="screen shot 2018-06-20 at 23 06 06" src="https://user-images.githubusercontent.com/12562/41670669-1bc71204-74df-11e8-9686-af1abc2dd6fd.png">

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If you're still experiencing the problem, please let us know and we will reopen this issue.
