### ISSUE TITLE
Invalid workspace name error message can be misleading

### ISSUE THREAD

**Issue by jay-jlm** [prisma/prisma-cloud-feedback#165]
Error reads like this:
"5xyz~abcd is not a valid name for a service name."

For the naive user, a tilde is being added which is causing this error when in fact the offending bit is the digit character in the beginning.

Moving the digit to the middle fixes the issue

Suggested behaviour:  folder separator (5xyz/abcd) or subdomain separator (5xyz.abcd) could be more intuitive for most people.

**Comment by lydiahallie** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!
