### ISSUE TITLE
Add support for digits in the beginning of workspace names

### ISSUE THREAD

**Issue by jay-jlm** [prisma/prisma-cloud-feedback#166]
> "5xxxx~xxxxxx is not a valid name for a service name."

Moving the digit to the middle fixes the error, but that's not ideal.
Lots of company names and product names use digits as the first character so it's very limiting that this is not currently supported.

**Comment by lydiahallie** [comment]
Thanks for reporting @jay-jlm. This is a limitation due to how we handle the workspace slug in our system. It's not something we want to change in the foreseeable future, so we're closing this issue.
