### ISSUE TITLE
Heroku Deployment Connecting to an existing DB

### ISSUE THREAD

**Issue by Jhony0311** [prisma/prisma-cloud-feedback#170]
Trying to use the Heroku Deployment I I'm finding some issues. What I tried was this:
1. According to the video tutorial, I go to Prisma Cloud, and on the server section I create a new server.
2. On "Set up a database" I chose "Connect to an existing database".
3. I picked PostgreSQL and fill the information, checking also the SSL connection checkbox. Also leave blank the schema field since I already have the schema on files locally and it says optional.
4. I picked Heroku as provider since is where I have my database created.
5. After choosing Heroku I get an endless spinner for "Create a new server" screen as well as some errors on the console for promises breaking. Here are some additional images for that.
![Endless Spinner](https://user-images.githubusercontent.com/6932538/42051022-4f1ebf52-7ad0-11e8-9a55-c7211fb7eba2.png)
![Errors in console](https://user-images.githubusercontent.com/6932538/42051033-55788a68-7ad0-11e8-9357-6536c13fdb79.png)

Additional Context:
- I have a project already created on Heroku with the same name of the server I'm trying to create on Prisma.
- The database already has content and tables created using Prisma CLI on my local with a project connected to that database.
- Confirming that also fails with a different name that is not the same for the Heroku project I have already created.

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If this is still an issue, please let us know and we'll reopen this!
