### ISSUE TITLE
Not possible to re-use Heroku on multiple workspaces

### ISSUE THREAD

**Issue by Lucas-Geitner** [prisma/prisma-cloud-feedback#172]
Heroku was able to connect the first time, 

When i tried to add him in another worspace it doesn't reconize the token and it refuse to create a new  DB / Seerver : 

<img width="804" alt="capture d ecran 2018-07-04 a 15 41 27" src="https://user-images.githubusercontent.com/20271305/42280549-54bb20f6-7fa1-11e8-87e9-09a1756ae2df.png">

<img width="1446" alt="capture d ecran 2018-07-04 a 15 40 55" src="https://user-images.githubusercontent.com/20271305/42280541-508a9a3e-7fa1-11e8-844c-2a99e49efa8f.png">

TypeError: e.data.herokuAccount is null[En savoir plus]

in the console : 

`Blocage du chargement du contenu mixte actif (mixed active content) « http://dynamodb.us-east-1.amazonaws.com/ping?x=dfh6325bxra88cnBgCTHvklb »[En savoir plus]
raven.min.js:2:12017
TypeError: NetworkError when attempting to fetch resource.[En savoir plus] raven.min.js:2:12018
Error: main.163e73bd.js:1:573394
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.cloud.prisma.sh/. Raison : échec de la requête CORS.
Blocage du chargement du contenu mixte actif (mixed active content) « http://dynamodb.us-east-1.amazonaws.com/ping?x=KzKzw4nHb10FAivwkPBBQyUe »[En savoir plus]
raven.min.js:2:12017
TypeError: NetworkError when attempting to fetch resource.[En savoir plus] raven.min.js:2:12018
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.cloud.prisma.sh/. Raison : échec de la requête CORS.
Error: main.163e73bd.js:1:573394
TypeError: NetworkError when attempting to fetch resource.[En savoir plus]
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.cloud.prisma.sh/. Raison : échec de la requête CORS.
TypeError: NetworkError when attempting to fetch resource.[En savoir plus]
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://api.cloud.prisma.sh/. Raison : échec de la requête CORS.
Error: main.163e73bd.js:1:573394
La connexion avec wss://nexus-websocket-b.intercom.io/pubsub/5-IutwfVRI7PSYjKRr4PSrGyBCD_z8vZbs_t36ZFwtUbOyvDO5fvyNikWp7rSq_v27wYFsWnV-8jQ-KNcZYCLILT55gbndbQdlUmDK?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.6-javascript&X-Atmosphere-Transport=websocket&X-atmo-protocol=true&X-Nexus-Version=0.4.52 a été interrompue pendant le chargement de la page. frame.3a2d5888.js:1:2283719
La connexion avec wss://nexus-websocket-a.intercom.io/pubsub/5-IutwfVRI7PSYjKRr4PSrGyBCD_z8vZbs_t36ZFwtUbOyvDO5fvyNikWp7rSq_v27wYFsWnV-8jQ-KNcZYCLILT55gbndbQdlUmDK?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.6-javascript&X-Atmosphere-Transport=websocket&X-atmo-protocol=true&X-Nexus-Version=0.4.52 a été interrompue pendant le chargement de la page.`

**Comment by marktani** [comment]
We should consider to support using one Heroku account with multiple workspaces

**Comment by MartineauCarl** [comment]
I have a similar issue: I had two workspaces, one i connected to Heroku and the other one not. I deleted the connected one and now I can't connect to Heroku with my remaining one as I get the same error message as above. Anyway to reset all Heroku connections associated with an account?

Thanks!

**Comment by lydiahallie** [comment]
Thanks for reporting! This has been fixed, you can now link one Heroku account to multiple workspaces.
