### ISSUE TITLE
Graceful error message for duplicate workspace name

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#180]
## Actual behaviour

![image](https://user-images.githubusercontent.com/1780597/42446943-5fcd827e-8378-11e8-90f8-8d2e33a914dc.png)

## Expected behaviour

* return a human-readable error message like "This workspace slug already exists. Choose another one."

* bonus: proactively catch this error before the user clicks on "Create Workspace" with a little validation in the slug input field

## Reproduction

* create a workspace with slug `test`

**Comment by lydiahallie** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!
