### ISSUE TITLE
Deleting a workspace is stuck

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#181]
## Actual behaviour

After deleting a workspace, the view is stuck on the settings of the workspace. I can even click around in the tabs "Workspace", "Team", "Billing" for some while. Then I get some error messages and am redirected to the previous workspace's default page.

## Expected behaviour

After deleting a workspace, I am redirected to the previous workspace's default page.

## Reproduction

* Navigate to the settings of a workspace and delete it.

**Comment by lydiahallie** [comment]
Thanks for reporting this, this is be fixed by now. If this is still an issue, let us know and we reopen this!
