### ISSUE TITLE
Can't connect Heroku account with non-Heroku database

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#185]
## Description

When setting up a Prisma server on Heroku using the Heroku integration, you can currently not connect to Heroku if you choose an existing database (not hosted at Heroku).

## Actual Behaviour

1. Enter the "Add Hosted Server" flow
2. Choose "Create a Server"
3. Choose "Connect to an existing database"
4. In the next step, you cannot login to Heroku

## Expected Behaviour

4. You can login to Heroku

## Workaround

Instead of choosing "existing database", you can choose "Create database" then create it at Heroku and login. Then navigate back and choose "existing database" and you are already connected to Heroku.

**Comment by lydiahallie** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!
