### ISSUE TITLE
New Heroku server does not show up on Prisma Cloud

### ISSUE THREAD

**Issue by Eiskis** [prisma/prisma-cloud-feedback#187]
I have added a new server to Heroku using the Prisma Cloud web UI. I went through the process as it's shown [in this image](https://i.imgur.com/YftVRrw.png).

I got the success message, where the last green button said "Set up new server" (or something to that effect) but instead of showing me another step, it took me back to the first screen in the flow where I can select the cloud provider. When I go back to the dashboard, I don't see the new server on the web UI, and it also does not show up in the CLI. On Heroku though, my new dyno shows up as expected.

I tried this multiple times, both with the same server name and with different ones. I now have two new dynos up on Heroku, but nothing new on Prisma Cloud.

The Prisma UI didn't show any errors at any point. I didn't see an obvious bug or any related errors in the console.

As a user I'm guessing there's an additional step in the wizard but there is something wrong with the button that's supposed to take me there; I didn't find any docs that would explain what this process should still include.

**Comment by Eiskis** [comment]
Are there any news on this? I'm really excited to set up my servers on Heroku, so I just tried it again with a different region and without ad blockers with the same results.

I'm happy to do anything I can to help debug this.

**Comment by lydiahallie** [comment]
Thanks for reporting @Eiskis!

If I understand your problem correctly, you're not creating the actual server after creating your database.

Note that the entire workflow of creating a server on Heroku requires you to finish two workflows:

1) **First we create your database.** After your database has been created successfully, the new dyno for your database will show up in your Heroku dashboard, however this isn't connected to any server just yet. As you haven't created a server yet, no server will show up on Prisma Cloud.

2) **Then we create your server.** After clicking on "set up a server" you should see the provider screen, where you can choose "Heroku" again as provider. After creating your server, the dyno is now connected to your new server, and you should see the server appear on your dashboard.

You finished step 1), which leads you to the start of 2) which you now have to complete by clicking on the "Heroku" button in the server providers list.
