### ISSUE TITLE
Unable to relink Prisma account to a new heroku account after removing the link in heroku 

### ISSUE THREAD

**Issue by designmatty** [prisma/prisma-cloud-feedback#193]
I ran into some issues a while ago when running through the new database setup process. After creating a new heroku account and following the new database wizard I didnt see my database show up on Prisma's side (but saw it in Heroku), I figured the accounts didn't link correctly so I unlinked my Prisma account from my Heroku account in the Heroku settings. Then I went through the following steps:

- Went to setup a new database with Prisma again
- Clicked on Connect to a new Heroku account
  -  _side note here: giving users the ability to link to already made heroku accounts would be ideal._
  - I expected to be directed to Heroku to create a new account but was taken to the "Create a new database" step in the wizard.
- On that page I got the following error: **Heroku account has already been added. Please select it in the heroku account selection.**
- (I've done this several times at this point and have tried clicking back to maybe select a Heroku account, which doesnt show since I removed the link on Heroku's side. If I don't click back to previous step and hit create database instead I get the error **Network error: Unexpected token < in JSON at position 0**)

I've tried numerous times to relink my prisma account with a heroku account but always get the same errors. It seems that Prisma is storing information about your linked heroku account, but doesnt give you the ability to remove said information.

**Comment by lydiahallie** [comment]
Thanks for reporting! This has been fixed by now. If this is still an issue, please let us know and we'll reopen this!
