### ISSUE TITLE
Heroku Integration Bug. "Couldn't Find That Docker Image".

### ISSUE THREAD

**Issue by marcaaron** [prisma/prisma-cloud-feedback#196]
Heroku integration is broken for me. PostgreSQL database gets created fine. But the Prisma Server creation errors out with the message: "Couldn't Find That Docker Image". 

![screen shot 249](https://user-images.githubusercontent.com/32969087/43691280-165f50e2-98cf-11e8-9dfb-9694c1b4ffdf.png)

Attempting to return to the previous page and create a new server result in the error: "GraphQL error: There is already a provision request for app my-app-name"
![screen shot 250](https://user-images.githubusercontent.com/32969087/43691316-94ce354c-98cf-11e8-8f64-5b159d91eb78.png)

**Comment by marcaaron** [comment]
Seems to have been intermittent or is now fixed. I was able to deploy a prisma server just now.

**Comment by marktani** [comment]
Awesome, thanks for the update @marcaaron 🙌

**Comment by Entryist** [comment]
^Hi, that was me. Happened again just now. I step through the database creation the same as the OP. Database creates fine, then I get the above error.

When this happened two days ago, after a few tries of failing to create a Standard-1X server it let me create a Hobby server. Just now I tried Standard-1X and Hobby and it gave the above message on both.

Note that the failed attempts created Heroku instances of type "heroku-16", but the successful attempt created an instance of type "container".

![tests](https://user-images.githubusercontent.com/14167547/43984390-2a92fcaa-9cb5-11e8-8944-3c12488f6921.png)

Failed attempts show the Heroku default screen at the app URL: https://ac-prisma-server.herokuapp.com/
And the one successful attempt shows the GraphQL playground: https://ac-prisma3.herokuapp.com/

Let me know if any other info from me will be helpful to debug this.

**Comment by ArnieGA** [comment]
Same thing happened to me.  However, in my case, the problem initiated after me deleting the server at prisma cloud and then trying to re-create it from scratch.
![image](https://user-images.githubusercontent.com/13170077/47532917-b1c93580-d87f-11e8-8db2-a1d646819cd0.png)

This popup closes by itself after a couple of seconds, and the "_Creating a database. This might take a few seconds..._" message never changes; the procedure never goes past beyond that point.

Any ideas on how I could fix this problem?

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If it's still an issue, let us know and we'll reopen this.

**Comment by RaffysWeb** [comment]
I'm having the same problem..when I try to create a new server I get an error message "Couldn't find that docker image."

**Comment by cidylle** [comment]
Same problem here:
<img width="974" alt="screen shot 2018-12-27 at 12 53 23 am" src="https://user-images.githubusercontent.com/1276782/50473489-fa7d9780-0971-11e9-96e4-1f8fc762035c.png">

**Comment by timbastin** [comment]
Same problem...

**Comment by christseng89** [comment]
Same problem to me as well 。。。。

**Comment by Dubmatth** [comment]
Same problem .... :)

**Comment by Charpell** [comment]
Same problem here :)

**Comment by LawJolla** [comment]
Same problem.  Also after deleting a server.

**Comment by GiancarlosIO** [comment]
can we re-open this issue?

**Comment by Charpell** [comment]
Mine has started working, I don't know how but I guess its a downtime. I suggest you'all try again
