### ISSUE TITLE
Stuck in creating DB screen for Heroku integration

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#201]
After creating the DB on Heroku and trying to create server on Heroku, you will be redirected to the `/create-heroku-db` instead of `/create-heroku-server`.

Manually navigating to `/create-heroku-server` works and you are able to proceed.

**Comment by sandman18** [comment]
When adding the url /create-heroku-server I am redirected to /services/onboarding/step-3 instead.

**Comment by marktani** [comment]
This should now be resolved. @sandman18 looks like you are running into a separate issue, can you reach out to support@prisma.io.

**Comment by sandman18** [comment]
Just set up a database and server.  Everything is working as it should!
