### ISSUE TITLE
Heroku server is created in version 1.11-beta

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#203]
Setting up a new Prisma server using the Heroku integration will pick version `1.11-beta` automatically.
Because it's fairly advanced to upgrade a Heroku server as of today (see #202), you should at least be able to pick the most recent versions.

As of today, this includes

* `1.14.0`
* `1.13.7`

I also think the latest `beta` and `alpha` versions should be available. As of today, this would be:

* `1.15-beta`
* `1.16-alpha`

**Comment by lydiahallie** [comment]
Thanks for reporting, this should be fixed by now! If this is still an issue, let us know and we reopen this.

**Comment by marcjulian** [comment]
I have created a new Prisma Server with the Heroku integration and it was setup with version `1.23.0`.  Should the version be the latest prisma version which is currently `1.25.7`?

<img width="1058" alt="screenshot 2019-02-02 at 22 13 51" src="https://user-images.githubusercontent.com/8985933/52169422-61902800-2738-11e9-9d35-2a4fb76e499a.png">
