### ISSUE TITLE
"Create an example" button not working

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma-cloud-feedback#204]
Hey there,

I signed up using GitHub, and tried to deploy a quick example.

When clicking the button, there's just a loader appearing less than a second, then everything appears again as if nothing happened.

**Comment by marktani** [comment]
Can you share a screenshot, @Weakky?

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/44160268-31859780-a0ba-11e8-991b-19b2154e2b5a.png)

I see, you mean this button! 🙂

**Comment by Weakky** [comment]
Here's what is happening :) http://recordit.co/yL4XCGaKZn

**Comment by timsuchanek** [comment]
Thanks for reporting! We just deployed a fix. If it's not fixed for you, let us know and we reopen the issue.

**Comment by Weakky** [comment]
Hohai @timsuchanek,

I'm not sure if this is related to your fix, but right now, my "Services" tab is completely empty. I tried to log out/log in, nothing changes.

<img width="1680" alt="capture d ecran 2018-08-23 a 13 47 04" src="https://user-images.githubusercontent.com/25233379/44523749-53df6c80-a6db-11e8-8d28-775b2e770af9.png">
