### ISSUE TITLE
Data Browser order types alphabetically

### ISSUE THREAD

**Issue by LawJolla** [prisma/prisma-cloud-feedback#206]
I think it'd be a nice user enhancement to order the data browser types alphabetically.  The following gets a bit unruly as the types grow.

Thanks for the incredible work!

![image 2018-08-21 at 1 26 07 pm](https://user-images.githubusercontent.com/17485128/44427216-c880a280-a545-11e8-87dd-606b3ef697c0.png)

**Comment by lydiahallie** [comment]
Thank you for your feedback! This feature has been implemented now.
