### ISSUE TITLE
You can give a workspace an invalid name

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#207]
You can for example create a new workspace with name `12312312321test`. This will result in the following error when navigating around in the workspace and a blank screen:

![image](https://user-images.githubusercontent.com/1780597/44595896-c5e2af00-a7ca-11e8-9a15-8b935f4e5314.png)

**Comment by lydiahallie** [comment]
This is fixed by now. If it's still an issue, let us know and we reopen this!

**Comment by cbodtorf** [comment]
I used oauth wtih github. My github name contains japanese characters.

The workspace was named with those characters, and the slug was converted into something that appears to be invalid.

name: ケーレブ
slug: -ffe764

I was able to delete it, but it did return some errors
