### ISSUE TITLE
Cannot create new server using Heroku Integration

### ISSUE THREAD

**Issue by uufish** [prisma/prisma-cloud-feedback#214]
![____________________________2018-10-02_15 44 16](https://user-images.githubusercontent.com/8127869/46339033-f3d5d180-c65b-11e8-8ba7-732508b3a1b3.png)

Console in DevTools.

<img width="1440" alt="____________________________2018-10-02_15 45 26" src="https://user-images.githubusercontent.com/8127869/46339045-f9331c00-c65b-11e8-8548-5cc6852b5d90.png">

**Comment by nunsie** [comment]
Also experiencing the above, steps to reproduce:

Add Server > Create Server > Connect to an existing database > Postgres (was an aws rds instance in my case) > Connect to Database > Connects successfully then hangs on the next step as shown above

**Comment by uufish** [comment]
In my case:
Add Server > Create Server > Connect to an existing database > MySQL (Cloud SQL) > Connect to Database > Connects successfully > ERROR

**Comment by HyveMynd** [comment]
Seeing the same when I try to do anything associated with heroku.

**Comment by HyveMynd** [comment]
knock knock. Any news? Has anyone else been able to fix it?

**Comment by uufish** [comment]
@HyveMynd You can deploy Docker using NOW and connect Prisma cloud.

https://github.com/develomark/prisma-now

and, you have to use v1.

```
"features": {
  "cloud": "v1"
},
```

**Comment by lydiahallie** [comment]
Thanks for reporting, this should be fixed by now! If this is still an issue, let us know and we reopen this.
