### ISSUE TITLE
Endpoints covers some links in sidebar

### ISSUE THREAD

**Issue by Huvik** [prisma/prisma-cloud-feedback#218]
Endpoints covers Metrics, Deployments, Playground if there are too many types defined
![](https://i.imgur.com/WR4co2W.png)

**Comment by jhalborg** [comment]
In general, the sidebar is a bit messy when the datamodel and number of entries grow:

![image](https://user-images.githubusercontent.com/6643672/46791281-12655800-cd41-11e8-9b6b-f97f3e4436f9.png)

**Comment by lydiahallie** [comment]
Thanks for reporting this, these issues should be fixed by now.  If there are still issues, let us know and we reopen this!
