### ISSUE TITLE
Add linked Heroku Account to all Workspaces

### ISSUE THREAD

**Issue by aaronholla** [prisma/prisma-cloud-feedback#226]
You can link a Heroku account in one workspace while setting up a new Prisma Server. Once it is linked in the workspace when setting up a new server in this workspace this account will be listed and you can click it during setup. See image below ( email changed for privacy )

<img src="https://user-images.githubusercontent.com/2300298/47624256-f14a8880-daf0-11e8-8f85-892a8938de82.png" width="350">

But if you switch to a new workspace and setup a new server and choose heroku the linked account does not show up in the heroku account list. Only the "Connect to new Heroku account" button. If you click on this button to link your Heroku account with this workspace it will give you an error saying to select this account because it is already linked. But there is no option for that account in the workspaces that it was not originally linked.

![screen shot 2018-10-28 at 8 45 49 pm](https://user-images.githubusercontent.com/2300298/47624455-4c7d7a80-daf3-11e8-9bdd-5036983dc2ec.png)

After this error it will continue on anyway to the next screen to create the database on heroku. But once clicked to create you get the next error saying that account is not part of the workspace.

![screen shot 2018-10-28 at 8 52 22 pm](https://user-images.githubusercontent.com/2300298/47624492-b138d500-daf3-11e8-852d-10dcf9967ca6.png)

There are a few other issues that are similar (#200 , #193, etc.), however this is a different issue all together. I have heroku linked and it all works fine I just can only access my heroku account from one workspace only. Please add the linked heroku accounts to all workspaces in the account selection step.

**Comment by lydiahallie** [comment]
This feature has been implemented now! You can now link a Heroku account to multiple workspaces.

**Comment by aaronholla** [comment]
Works like a charm! Thank you!
