### ISSUE TITLE
Incorrect information in server view

### ISSUE THREAD

**Issue by kuldar** [prisma/prisma-cloud-feedback#235]
There seem to be some erroneous info in the server view. 

- All the indicators are showing "Not available" even if the servers are actually available.
- The endpoint url seems to be missing for Heroku servers
- The descriptions for demo servers _seem_ to be incorrect

![kapture 2018-12-13 at 17 12 19](https://user-images.githubusercontent.com/1710629/49951654-b662af80-fefa-11e8-9f38-9cbd730a0974.gif)

**Comment by divyenduz** [comment]
This one is resolved now. Please close this issue if you think that it is indeed fixed 🙏
