### ISSUE TITLE
Unable to deploy a new heroku server from prisma cloud

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma-cloud-feedback#239]
![image](https://user-images.githubusercontent.com/22195362/50473432-e625b300-09e2-11e9-977d-13ba8de2d194.png)

If you try to deploy a new Heroku server from prisma cloud it will fail and will say cannot find docker image

**Addional context**:

latest prisma version is 1.23.2. A user reported that manually pushing the `1.23.2-heroku` tag works

**To reproduce**:

Just try to deploy a new Heroku server

**Comment by pantharshit00** [comment]
This has been fixed for now.

**Comment by pantharshit00** [comment]
I can still trigger this same issue.

**Comment by t3rminus** [comment]
I'm experiencing this as well.
It looks like this is an ongoing, intermittent problem: #196

**Comment by sulkowski** [comment]
It has just worked for me 🎉
