### ISSUE TITLE
Services switcher don't work on right side

### ISSUE THREAD

**Issue by Huvik** [prisma/prisma-cloud-feedback#25]
When clicking on arrow on right side select don't trigger
![](https://i.imgur.com/ByLJrl0.png)

**Comment by timsuchanek** [comment]
Fixed :)

**Comment by Huvik** [comment]
I think is still problem 
![](https://i.imgur.com/Y6RCHrh.gif)

**Comment by marktani** [comment]
Can confirm, I also tried hard reloading.

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If you're still experiencing the problem, please let us know and we will reopen this issue.
