### ISSUE TITLE
Healthy status is not working

### ISSUE THREAD

**Issue by fabien0102** [prisma/prisma-cloud-feedback#40]
I've deleted my amazon database and prisma (after 1 hour) say that my service is `Healthy`.

I'm quite sure that is not really true ^^

**Comment by gentle-noah** [comment]
I think this is related to [#39](https://github.com/graphcool/prisma-cloud-feedback/issues/39)

**Comment by marktani** [comment]
This is fixed :slightly_smiling_face:

**Comment by marktani** [comment]
@divyenduz is still experiencing this

**Comment by divyenduz** [comment]
<img width="992" alt="screen shot 2018-06-20 at 3 28 28 pm" src="https://user-images.githubusercontent.com/746482/41661773-b89497ea-749f-11e8-9d1b-3f53c87520bb.png">

Keeping this dead cluster around for this issue.

**Comment by divyenduz** [comment]
<img width="989" alt="screen shot 2018-06-20 at 6 59 46 pm" src="https://user-images.githubusercontent.com/746482/41673124-2cae7b98-74bc-11e8-8a25-5a7157b50b0d.png">

It took a while but cloud shows "Not reachable" now.

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If you're still experiencing the problem, please let us know and we will reopen this issue.

**Comment by kode8** [comment]
Hhd nothing but problems with Prisma, it's incredibly buggy. It auto deploys a Heroku app yet says the server is unreachable.

**Comment by AviIhej** [comment]
Do you know why my Graphql API that is deployed to heroku through prisma cloud is so buggy?
When my client queries the API, the response takes a good 1-2 minutes to come through.
Half the time, the server says "not reachable". The other half it says "healthy". Any Idea why???
