### ISSUE TITLE
Issue creating cluster

### ISSUE THREAD

**Issue by jhalvorson** [prisma/prisma-cloud-feedback#56]
When creating a cluster I filled out my details and made a mistake on the card details, I amended the error, pressed the 'create cluster' button again and it hasn't stopped spinning.

Button has been spinning for approx 15-20 mins, when I view the '/clusters' page I can see that the cluster hasn't been created yet.

**Comment by jhalvorson** [comment]
Upon refresh and filling out details again all appears fine.

Looks like once the button has been pressed and if there's an error on the form the button doesn't reset so you can't properly press it again to create your cluster.

**Comment by lydiahallie** [comment]
Thanks for reporting! This should be fixed by now. If you're still experiencing the problem, please let us know and we will reopen this issue.
