### ISSUE TITLE
Can't change account slug

### ISSUE THREAD

**Issue by sedubois** [prisma/prisma-cloud-feedback#71]
Unable to change my slug on `https://app.prisma.sh/<slug>/settings`. Nothing happens when clicking "Save Changes". No message in console. Using Firefox.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!

**Comment by sedubois** [comment]
Thanks but I couldn't change the slug same visual behaviour as in OP, and the console now shows:

<img width="935" alt="screen shot 2018-06-07 at 15 56 54" src="https://user-images.githubusercontent.com/4217871/41101003-88eb9f04-6a6b-11e8-8db6-3bef547ed764.png">

**Comment by timsuchanek** [comment]
This indeed couldn't work, I found the problem and fixed it. Please let me know if it's finally fixed for you. Thanks!

**Comment by sedubois** [comment]
Still not :) Same behaviour, with console below:

<img width="834" alt="screen shot 2018-06-21 at 12 12 21" src="https://user-images.githubusercontent.com/4217871/41709685-7acecd74-754c-11e8-8ca6-9d93b0352af5.png">

**Comment by schickling** [comment]
Closed in favor of #241
