### ISSUE TITLE
Set fields to null when creating or updating

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#74]
It's currently not possible to set fields to `null`. Neither when creating or updating a node. I tested this with strings and ints.

**Comment by timsuchanek** [comment]
We need a design for this state first.
![image](https://user-images.githubusercontent.com/1094804/40977112-5ba95320-68d0-11e8-8a58-a78b38fbcc19.png)

This is how we solved it in Graphcool:
![image](https://user-images.githubusercontent.com/1094804/40977281-c873fad2-68d0-11e8-8d4c-aead451c7558.png)

**Comment by kuldar** [comment]
One null button coming right up.

![nulling a field](https://user-images.githubusercontent.com/1710629/42888993-ae23a150-8aa9-11e8-8590-7189826cc12a.png)

**Comment by lydiahallie** [comment]
This has been implemented!
