### ISSUE TITLE
Sharing a playground does not work

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-cloud-feedback#77]
<img width="426" alt="bildschirmfoto 2018-03-06 um 15 21 43" src="https://user-images.githubusercontent.com/16278407/37038755-f27410f0-2155-11e8-8f6a-1e67147c9f87.png">

**Comment by lydiahallie** [comment]
Thanks for reporting this, this is be fixed by now. If this is still an issue, let us know and we reopen this!
