### ISSUE TITLE
Make service endpoint available in Console

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#79]
Should give same information as `prisma info`

**Comment by timsuchanek** [comment]
![image](https://user-images.githubusercontent.com/1094804/40976290-f58de648-68cd-11e8-822d-61eb771e10ad.png)

This means we need the WS & HTTP endpoint in the info

**Comment by kuldar** [comment]
So we currently had the endpoint planned for the sidebar footer, but I'm not in love with that solution. It only works for copy-pasting the endpoint and not so much for referencing/double-checking the endpoints. 

Would there also be any other service metadata that we would need to show?

**Comment by marktani** [comment]
This is now implemented! 🎉
