### ISSUE TITLE
Gracefully handle connection errors on cluster creation

### ISSUE THREAD

**Issue by marktani** [prisma/prisma-cloud-feedback#95]
When creating a cluster on a DB that doesn't have the correct inbound rules, the request times out and this is printed:

```
Error while testing database connection:
GraphQL error: connect ETIMEDOUT
```

Instead, a helpful error message should be shown. Something like

> The connection to the database timed out. Please double check your credentials, and ensure that inbound HTTP requests are allowed.

**Comment by rsnay** [comment]
Excellent idea! I ran into this issue—I could successfully connect to a database from my local machine, but not from Prisma. I didn't realize that AWS RDS automatically added my current machine to the inbound traffic rules!

Could you also provide an example rule of what inbound rules are needed? E.g. if there's a specific IP or IP address range that the security rule can be restricted to, without having to allow traffic from any source.

**Comment by lydiahallie** [comment]
This is fixed by now. If this is still an issue, let us know and we'll reopen this!
